### ISSUE TITLE
<optgroup> Support for <select> Component

### ISSUE THREAD

**Issue by thyseus** [glhd/aire#113]
It would be neat if the Select Component could handle `<optgroup>`'s like:

```php
Aire::select([
  'group1' => ['group1option1', 'group1option2'],
  'group2' => ['group2option1', 'group2option2'],
])
```

generating

```html
<select>
 <optgroup label="group1"> ... </optgroup>
 <optgroup label="group2"> ... </optgroup>
</select>
```

**Comment by bogdankharchenko** [comment]
@thyseus https://github.com/glhd/aire/pull/97 - this is already possible.

**Comment by thyseus** [comment]
@bogdankharchenko thanks for that info! Did not find it in the documentation. Is this feature documented ?

**Comment by bogdankharchenko** [comment]
I don't believe it is documented - we will add some docs.
