### ISSUE TITLE
Bootstrap 5 support

### ISSUE THREAD

**Issue by 7henry767** [glhd/aire#114]
Hey,

nice project.

i just wanted to ask if a Bootstrap 5 theme is going to be added.

**Comment by inxilpro** [comment]
I don't think we have plans to add a Bootstrap 5 theme, but I'd be happy to link to one if someone else wants to take on the maintenance of it.

/cc @bogdankharchenko

**Comment by bogdankharchenko** [comment]
@7henry767 we can add it - it will be part of https://github.com/glhd/aire-bootstrap repo - in the mean time you can just see how theming works in that repo and you can make those changes locally
