### ISSUE TITLE
Ability to use with livewire

### ISSUE THREAD

**Issue by wardy484** [glhd/aire#16]
**Is your feature request related to a problem? Please describe.**
I've started using [Livewire](https://github.com/calebporzio/livewire) and it makes doing more complex operations with blade very nice however I can't see an obvious way to use the wire attributes on aire elements.

**Describe the solution you'd like**
The ability to chain something like `->wire('click', 'actionName')` onto aire elements.

**Additional context**
I've since forked the package and have so far created a trait to allow this to be added to elements but I'm not sure if it's something that would have a place in the core package.

**Comment by inxilpro** [comment]
I love this idea, but feel like it would be best done as an Aire package. I’d be happy to add whatever is necessary to make it possible. We’d probably be able to get away with making the `Element` class macroable, and then you could just register your helper there. 

What do you think?

**Comment by wardy484** [comment]
Yeah I think you're right macro's would probably be sufficient for this. 

I ended up with just a single method on Element while tinkering. Not sure how you would make it a plugin for Aire. 

`    /**
     * Supports using aire with LiveWire
     *
     * @param string|array $attribute attributes or attribute + modifiers
     * @param string $action
     * @return self
     */
	public function wire($attribute, string $action) : self
	{	
		if (is_array($attribute)) {
			$attribute = implode(".", $attribute);
		}

		$this->attributes->set('wire:' . $attribute, $action);

		return $this;
	}`

**Comment by inxilpro** [comment]
Does just adding the `wire:` attribute work? I wasn’t sure if livewire was tapping into the blade compiler and messing with the attributes or if it was all handled in JS.

**Comment by wardy484** [comment]
It seems to work fine. I believe the mark up is rendered by blade. The JavaScript seems to be mainly for replacing DOM which is but all the html comes from the server.

**Comment by inxilpro** [comment]
Version `1.5.1` adds macro support. Let me know if you run into any issues.

I also did want to note that you should be able to do this even before `1.5.1`:

```php
aire()->input()->addAttribute('wire:click', 'actionName');
```
