### ISSUE TITLE
Collection::replaceRecursive does not exist

### ISSUE THREAD

**Issue by mokhosh** [glhd/aire#17]
**Describe the bug**
I was gonna try Aire for the first time and I couldn't create my first form.

** Have you published the Aire config file? **
No

** Have you added custom Aire views? **
No

**To Reproduce**
1. Install Aire
2. Open an Aire form
3. Try to insert a simple input

**Expected behavior**
Following the documentation example should give you a simple form instead of an error.

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Latest version

**Comment by mokhosh** [comment]
I played around with it and seems like it doesn't even open the form.
I removed form elements and kept the `{{ Aire::open() }}` but it just messes up the code. It removes some parts of the code and makes the remaining render in the wrong part of the layout for some reason!

**Comment by inxilpro** [comment]
What version of Laravel are you using? Can you post more of the stack trace for the error?

**Comment by mokhosh** [comment]
Thanks for the reply. Yeah, it must have been something with laravel:
```
  - Updating laravel/framework (v5.8.26 => v5.8.32): Loading from cache
```
a `composer update` solved the problem.
