### ISSUE TITLE
Use the same code for update/create

### ISSUE THREAD

**Issue by mokhosh** [glhd/aire#18]
If I want to use the same blade file for both updating and creating a model I have to write something like this:
```php
Aire::open()->route(isset($role) ? 'role.update' : 'role.store', $role ?? null)->bind($role ?? null)
```

Is there a cleaner way to do this?
Can we just give it a variable name and let `Aire` decide if it's set and do the rest accordingly?

Also for things like submit button text:
```php
{{ Aire::submit( isset($role) ? __('app.update_role') : __('app.new_role') ) }}
```

**Comment by inxilpro** [comment]
Take a look at the `resourceful` helper.

```php
// These are essentially the same:
Aire::resourceful($user);
Aire::open()->route($user->exists ? 'users.update' : 'users.store')->bind($user);
```

In your controller, you would do something like:

```php
class UsersController
{
  public function create() {
    return view('users.create', ['user' => new User()]);
  }
  
  public function edit(User $user) {
    return view('users.create', compact('user'));
  }
}
```

By passing down an instantiated `User` no matter what, Aire can take advantage of any default attributes or mutators that you've set during model binding to set good defaults.

As for the submit button—I've been wanting the same thing and will probably implement something like `Aire::submitResource($store_label = 'Create', $update_label => 'Save Changes')`

That'll probably be in the next release.

**Comment by mokhosh** [comment]
> Take a look at the `resourceful` helper.

Did I miss this in the documentation?

**Comment by inxilpro** [comment]
Good catch! I've added a section about resourceful routes to the docs. Most things are pretty well documented, but feel free to submit a PR if you notice anything missing.

**Comment by mokhosh** [comment]
Just one more thing. The code you provided in the docs didn't work as it closed the form right after opening it. After I red the code I figured you have to do something like this:
```
Aire::resourceful($user)->open();
```
