### ISSUE TITLE
Image component : nothing on screen with Bootstrap

### ISSUE THREAD

**Issue by LPABelgium** [glhd/aire#19]
Hi !
Not really a bug I think but does your Image components work fine ?
I don't find the doc for this, and when I get it a try, don't see anything on screen (with Bootstrap theme).

Is it normal ? Have you some demo of this component ? Does it include image preview for the has-to-be-uploaded image and the old one ?

Thanks !

**Comment by inxilpro** [comment]
I’ll try to send over a demo shortly—I’m on my phone & getting ready to head on vacation, so it may take me a bit.

But generally, the image component is just an `<input type=“image”>` — so you need to add the attributes you would normally add. Something like the following should work:

`Aire::image()->src($image_url)->width(200)->height(100)`

**Comment by inxilpro** [comment]
Generally it’s better to just use a button with an image tag inside of it…

**Comment by inxilpro** [comment]
Yep, I just confirmed that this works:

```php
Aire::image()->src('https://placeimg.com/200/100/animals')->width(200)->height(100);
```

Again, `<input type="image" />` is generally frowned upon, but if you need to use it, that should work.

Were you expecting `Aire::image()` to be an image upload component?

**Comment by LPABelgium** [comment]
Hi !
First of all, thanks for your quick response ;)
Secondly, yes, I didn't take time to crawl sources and find how to deal with image() since in docs there's nothing which says that's there's something to do more than to use "Aire::image()".

So, I'll give it a next try ;)
Again, thanks for quick reply !
