### ISSUE TITLE
Add disabled attribute for select options

### ISSUE THREAD

**Issue by DavidWarlock** [glhd/aire#20]
I think it's necesary to add this:

`<option val="1" disabled>Disable Option<option>`

Can be something like a function receiving an array with the values that will be disabled:
```
Aire::select($array,
                    'select', 
                    'Select'
               )
               ->value(1)
               ->disabledOptions([2,3,5]);
```
Idk it just a suggest. Btw nice work ;)

**Comment by inxilpro** [comment]
The main item for the next release is better handling of select options (option groups, disabled options, styling options, etc). Should be in a week or two! (I’m on vacation, so it might take a bit longer than usual.)

**Comment by Jossnaz** [comment]
2 weeks was what, 1.5 years ago?

was this fixed?

**Comment by inxilpro** [comment]
Hah, yeah. The improved select functionality ended up getting put on the backburner in favor of other functionality. It's fairly rare that we run into situations where you really need to have a lot of control over individual options in a select. Should happen some time, or you're welcome to submit a PR if you have a specific use-case that you need support for.

**Comment by Jossnaz** [comment]
I was more concerned if this project is alive or not honestly. You are right it's not very important.
