### ISSUE TITLE
Extend my custom element

### ISSUE THREAD

**Issue by b1nj** [glhd/aire#23]
Hello,
Is there a simple way to extend aire for my customs elementst?
Like Google maps lat/lng, mardown wysiwyg, drag and drop upload file...

**Comment by inxilpro** [comment]
Right now there's not a straightforward way to to add something like `Aire::myElement()`, but you can easily add a `class MyElement extends \Galahad\Aire\Elements\Element {}` and then instantiate it with your own helper. 

I would like to add a few extension points, but I haven't figured out the most ergonomic way to do that… I'm certainly open to suggestions.

The other issue is that ideally we'd have a way to implement it such that IDEs could easily understand and provide refactoring and autocomplete support, but things like the `Macroable` trait don't do that. Once I find something that I'm happy with I'll be adding better extension support to the core library.

**Comment by b1nj** [comment]
thank you, I'll look at this quietly
