### ISSUE TITLE
Support 'data-' attribute

### ISSUE THREAD

**Issue by mohamedsabil83** [glhd/aire#24]
it will be useful if package support adding custom `data-`.

**Comment by inxilpro** [comment]
There’s a `data()` method on elements. `Aire::input()->data(‘foo’, ‘bar’)` will result in `data-foo=“bar”` on the input tag.

**Comment by inxilpro** [comment]
Not all the attribute methods are in the docs yet. I’ll be sure to add this. All elements have methods for all attributes they support, on an element-by-element basis.

**Comment by mohamedsabil83** [comment]
I just found it after searching entire the code. I feel it a worth package and I'll try it now.
What can I do to help especially in tailwind custom form?
Also, can I add an AR translation or you have another plan for translation?

**Comment by mohamedsabil83** [comment]
What if I want to add custom attributes like vue attributes e.g.:
```
->attribute('v-on:click', 'something')?
```

**Comment by mohamedsabil83** [comment]
> What if I want to add custom attributes like vue attributes e.g.:
> 
> ```
> ->attribute('v-on:click', 'something')?
> ```

Anyone who reads this and is interested, It's done like this: `->setAttribute('v-on:click', 'something')`
Thank you again @inxilpro for the valuable package.

**Comment by inxilpro** [comment]
There's now [documentation for most element attribute setters](https://glhd.github.io/aire/working-with-elements) (I just pushed the docs, so it might take a moment for Github to update the docs site).

**Comment by inxilpro** [comment]
> What can I do to help especially in tailwind custom form?

Really it just needs to be tested in the wild. It should be ready to use in theory, but I just haven't had the chance to play with it and make sure there's nothing missing.

> Also, can I add an AR translation or you have another plan for translation?

I haven't done much work in terms of translation yet. The only thing that exists at the moment is the translation for the summary helper. You're welcome to submit a PR for that, though!
