### ISSUE TITLE
Default summary act as verbose

### ISSUE THREAD

**Issue by mohamedsabil83** [glhd/aire#26]
**Need correction**
Unlike mentioned in docs, default `summary()` action is `summary()->verbose()` not `summary()->simple()`

**Comment by inxilpro** [comment]
Here's the source code for the `Summary` element. As you can see, `verbose` is set to `false` by default. Where are you seeing otherwise?

```php
class Summary extends Element
{
  public $name = 'summary';
  protected $grouped = false;
  protected $view_data = [
    'verbose' => false,
  ];

  public function verbose(bool $verbose = true) : self
  {
    $this->view_data['verbose'] = $verbose;
    return $this;
  }

  public function simple() : self
  {
    return $this->verbose(false);
  }
}
```

**Comment by inxilpro** [comment]
Oh! I see it. The helper method sets it to verbose by default. I'll fix that!
