### ISSUE TITLE
A placeholder for select

### ISSUE THREAD

**Issue by mohamedsabil83** [glhd/aire#27]
**Is your feature request related to a problem? Please describe.**
No, it's an enhancement request.

Many times we need to add a place holder, a prepend option w/ value, to the normal options list. is it already exist?

**Comment by inxilpro** [comment]
You can use `prependEmptyOption()`:

```php
Aire::select([1 => 'One', 2 => 'Two'])->prependEmptyOption('Pick a number');
```

This will result in:

```html
<select>
  <option value="">Pick a number</option>
  <option value="1">One</option>
  <option value="2">Two</option>
</select>
```

The second parameter of `prependEmptyOption` is the "empty" value—which defaults to `""`
