### ISSUE TITLE
Resourceful Helper requires open() unlike documented

### ISSUE THREAD

**Issue by Polfo** [glhd/aire#32]
The documentation on Resourceful Helper on page https://glhd.github.io/aire/api seems to indicate that `{{ Aire::resourceful(User::find(1)) }}` is an alternative to `{{ Aire::open()->route('users.update', 1)->bind(User::find(1))->put() }}`.

However, in my case at least,  `{{ Aire::resourceful($user) }}` does not work, while  `{{ Aire::open()->resourceful($user) }}` does work.

It does not work because of error message

> Trying to close a form that hasn't been opened.

If I remove the `Aire::close()`, then the` form` is closed immediately after `_token` and `_method` instead of after my `input` fields 

**Have you published the Aire config file?**
No

**Have you added custom Aire views?**
No

**What version does this affect?**
 - Laravel Version: 6.0.3
 - Aire Version: 1.7.1

**Comment by inxilpro** [comment]
Good catch! I'll update the docs.

**Comment by inxilpro** [comment]
Actually, the next release will work as the docs suggest. Calling `open()` will no longer be necessary for `route()` and `resourceful()`. Thanks!
