### ISSUE TITLE
Validation error not displayed because of class="d-none"

### ISSUE THREAD

**Issue by Polfo** [glhd/aire#33]
**Describe the bug**
When there is a validation error, it displayed through `Aire::summary()->verbose()`, and the individual input turns red, and the individual error message is present in the HTML, which is OK, but the error message is not displayed. 

This is an example HTML

    <div class="d-none" data-aire-component="errors" data-aire-for="name">
      <div>
        The name field is required.
      </div>
    </div>

**Expected behavior**
`class="d-none" ` seems suspect. I would expect something like `class="alert alert-warning"`

**Have you published the Aire config file?**
 No

**Have you added custom Aire views?**
No

**What version does this affect?**
 - Laravel Version: 6.0.3
 - Aire Version: 1.7.1
 - Aire Bootstrap Version: 1.0.0-beta.4

**Comment by Polfo** [comment]
![image](https://user-images.githubusercontent.com/10303392/64913980-321fb000-d74a-11e9-8307-f8c3c420e625.png)
![image](https://user-images.githubusercontent.com/10303392/64913993-55e2f600-d74a-11e9-9c25-0886a0127165.png)

**Comment by inxilpro** [comment]
@amberlampsio can you take a look? This seems to be Bootstrap-specific.

**Comment by amberlampsio** [comment]
Issue resolved by applying styling for summary block, https://github.com/glhd/aire-bootstrap/pull/8
