### ISSUE TITLE
Customized button still uses default background color

### ISSUE THREAD

**Issue by minthemiddle** [glhd/aire#37]
**Describe the bug**
When I customize the button, it still applies the default background `bg-blue-500`

**Have you published the Aire config file?**
Yes

**Have you added custom Aire views?**
No

**What version does this affect?**
 - Laravel Version: v6.0.3
 - Aire Version: 1.8.0

**To Reproduce**
1. Go to `config/aire.php`> default classes
2. Customize `button``

```php
'default_classes' => [
		'button' => 'text-secondary border-2 border-secondary bg-white',
	],
```

**Expected behavior**
Only my classes should determine the button layout

**Additional context**
- `*-secondary` has been created in Tailwind correctly.
----------------

If this is an issue with the way Aire renders a component, please provide the following additional information:

**Screenshots**
![image](https://user-images.githubusercontent.com/1950766/65373827-d5108680-dc82-11e9-87fb-d03e6b484a08.png)

**Desktop (please complete the following information):**
 - OS: iOS 10.14.6
 - Browser: Brave 0.68.132 Chromium: 76.0.3809.132

**Comment by inxilpro** [comment]
You need to override the default variant, too. This will be cleaned up in 2.0 most likely.

```php
[
'variant_classes' => [
		'button' => [
			'default' => [
				'display' => '',
				'size' => '',
				'color' => '',
			],
		],
	],
];
```
