### ISSUE TITLE
Concise notation for conditional checkbox (based on values from model)?

### ISSUE THREAD

**Issue by minthemiddle** [glhd/aire#43]
I want to use a checkbox to toggle the user setting `optout`.
Right now the only way to show the right status in the UI is with a Blade condition.

_Do you know an easier way to always show the right state in Aire (unchecked if `$user->optout == 0`, checked if `$user->optout == 1`)?_

```php
@if ($user->optout == 1)

{{ Aire::checkbox('optout', 'Opt out')->checked() }}

@else
{{ Aire::checkbox('optout', 'Opt out') }}
@endif

**Comment by inxilpro** [comment]
Try `defaultChecked(1 === $user->optout)` or binding the form to the user object. I’m on my phone right now—let me know if that doesn’t work and I’ll check when I’m at my laptop.

**Comment by inxilpro** [comment]
Just got back to my laptop. There are two ways to do this:

```php
{{ Aire::checkbox('optout', 'Opt out')->defaultChecked(1 === $user->optout) }}
```

Or:

```php
{{ Aire::bind($user) }}
{{ Aire::checkbox('optout', 'Opt out') }}
```

Calling `bind()` will bind all the user values to the form. Because `optout` is the name of the checkbox and also the name of the user attribute, it will automatically be checked if `$user->optout` is true.
