### ISSUE TITLE
Change structure of the field and changing dynamically theme

### ISSUE THREAD

**Issue by garbinmarcelo** [glhd/aire#44]
Would you like to do something like this, would it be possible? any tips?

I would like to change the structure of the field. Add HTML code for example make a checkbox with that code.

```html
<label class="kt-checkbox kt-checkbox--success">
  <input type="checkbox"> Success state
  <span></span>
</label>
```
![image](https://user-images.githubusercontent.com/9335588/67606782-ca04b680-f758-11e9-9e2b-55b7f9779b5b.png)

and if you could switch between themes. For example, on one page use the default theme and another bootstrap or your own theme.

**Comment by marcelogarbin** [comment]
@inxilpro Would you help me?

How can I use 2 themes at once by applying one of 2 to a specific form.

The idea here is to use one theme for the website part and another for the administrative panel part of it, where the HTML structure is different.

I've looked at the theme documentation (https://glhd.github.io/aire/themes), but I don't know and haven't figured out how to use selecting a specific theme for a particular form.

It is possible?

Thank you for your help right now.

**Comment by inxilpro** [comment]
Sorry! For some reason I’ve started missing notifications for this repo. You should be able to call `Aire:: setTheme` on the appropriate pages, although theming wasn’t really meant to be used in this way, so I can’t guarantee that it’ll work perfectly. 

Give that a shot and let me know how it works out. We may have to make some adjustments in the library to account for this use-case.

**Comment by inxilpro** [comment]
If using `Aire::setTheme` didn't do it, feel free to open another ticket. Gonna close this for now.
