### ISSUE TITLE
How to add link to checkbox label?

### ISSUE THREAD

**Issue by minthemiddle** [glhd/aire#47]
How can I add a link to a checkbox label (see screenshot below)?

`{{ Aire::input('checkbox', '<a href="#">Test</a>') }}` escapes the HTML, so does it when using `->helpText('<a href>')`

![grafik](https://user-images.githubusercontent.com/1950766/73170054-c25d0100-40fd-11ea-9c23-4d3c826d84e1.png)

**Comment by inxilpro** [comment]
Use `labelHtml()` (or you can also pass an `HtmlString` object in.

**Comment by minthemiddle** [comment]
Thanks

**Comment by minthemiddle** [comment]
Could you please elaborate on the `HtmlString` object, @inxilpro?

I cannot use the first approach when I have to pass a `route('name')` in the HTML.

This does not work (and I need both `'` and `"` within the HTML):
```
{{ Aire::checkbox('confirm_privacy', 'Datenschutz')->labelHTML('<a href="route('static.privacy')">Datenschutzerklärung</a> zustimmen') }}
```

**Comment by inxilpro** [comment]
It’s just regular PHP, so you can escape the string. Depending on what you want, do:

labelHTML('<a href="route(\'static.privacy\')">Datenschutzerklärung</a> zustimmen')

Or:

labelHTML('<a href="''.route('static.privacy').'">Datenschutzerklärung</a> zustimmen')
