### ISSUE TITLE
TypeError: right-hand side of 'in' should be an object, got undefined when validating _token field

### ISSUE THREAD

**Issue by laytan** [glhd/aire#48]
**Describe the bug**
I get this error when adding a form with a validation rule set, i fixed it temporarily by renaming Aire.js to Aire.min.js and changing line 2251 from:
`if ('errors' in refs[key] && refs[key].errors[0].childElementCount > 0) {`
to:
`if (refs[key] && 'errors' in refs[key] && refs[key].errors[0].childElementCount > 0) {`
With some logs i saw that it failed on trying to validate the _token field.

**Have you published the Aire config file?**
No

**Have you added custom Aire views?**
No

**What version does this affect?**
 - Laravel Version: [6.7.0]
 - Aire Version: [1.9.0]

**To Reproduce**
1. Create a form like
```
{{ Aire::open()->route('galaleries.store')->rules(['title' => 'required']) }}
    {{ Aire::input('title', 'Titel')->id('title')->autocomplete('off') }}
    {{ Aire::submit('Aanmaken') }}
{{ Aire::close() }}
```

**Expected behavior**
The form validates and does not show errors in logs

**Comment by inxilpro** [comment]
Should be fixed in 1.9.1. Thanks!
