### ISSUE TITLE
Support Laravel 7

### ISSUE THREAD

**Issue by minthemiddle** [glhd/aire#54]
Aire does not support Laravel 7 yet.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install glhd/aire 1.10.0
```

**Comment by inxilpro** [comment]
Should be ready this week

**Comment by mohamedsabil83** [comment]
Hey, Is it ready yet? I can install it as `dev-master` but in this case **aire-tailwind-custom-forms** not installed.

**Comment by minthemiddle** [comment]
Any help needed with this @inxilpro ?

**Comment by inxilpro** [comment]
Aire’s latest release has Laravel 7 support. I’ll make sure the themes do, too. That may have been an oversight.

**Comment by minthemiddle** [comment]
Solved by https://github.com/glhd/aire/releases/tag/2.0.0
