### ISSUE TITLE
Validation messages divs have no classes when using Bootstrap

### ISSUE THREAD

**Issue by alessandrotesoro** [glhd/aire#63]
**Describe the bug**
Hi there, I'm relatively new to Laravel and started using your package to generate forms in my app. I've noticed that when using the Bootstrap templates, the containers of the error messages have an empty class attribute.

This only happens when using the bootstrap template. When removed, classes appear correctly.

Any idea how to fix the issue? I did also try to publish the config file but nothing changed, still no classes.

**Have you published the Aire config file?**
No

**Have you added custom Aire views?**
No

**To Reproduce**
1. Create a form
2. Add some validation rules
3. Add the bootstrap template
4. Submit the form in a way that triggers error messages
5. Inspect the output via browser's console to see the class attribute empty

**Expected behavior**
Divs should be populated with classes

**Comment by inxilpro** [comment]
@amberlampsio Can you take a look at this?

**Comment by amberlampsio** [comment]
@alessandrotesoro sorry for taking for ever, someone actually submitted a PR which never got merged, https://github.com/glhd/aire-bootstrap/pull/3 -- we will push out a release shortly.
