### ISSUE TITLE
Support for error bags

### ISSUE THREAD

**Issue by antergos98** [glhd/aire#65]
I have multiple forms on the same page and I'm using Laravel's error bags to store errors in the correct bag. It it doesn't already exist, it'd be great to specify which error bag to use for server validation.

`{{ Aire::open()->withErrorBag('updatePassword') }}`

Then, errors would be displayed properly.

**Comment by inxilpro** [comment]
Interesting. I never use different error bags. Would you be willing to submit a PR?

**Comment by inxilpro** [comment]
This ends up being more complicated than I'd like, and I haven't seen anyone else ask for this feature. I'm going to close this and the PR for now.
