### ISSUE TITLE
How to Add asterisk to required fields ?

### ISSUE THREAD

**Issue by lhoucinecherif** [glhd/aire#68]
**Describe the bug**
can't find a clear way to add red asterisk to input required lables

**Have you published the Aire config file?**
Yes

**Have you added custom Aire views?**
Yes

**What version does this affect?**
"laravel/framework": "^7.24",
"glhd/aire": "^2.3",
"glhd/aire-bootstrap": "^2.0",

**To Reproduce**
1. Just try to show html asterisks on the required field label ' <span class="text-danger">*</span>'

**Expected behavior**
A way to enable html on the input labels if needed

**Comment by inxilpro** [comment]
You should be able to publish your own label.blade.php file to present the labels however you want.
