### ISSUE TITLE
how would you add your own component?

### ISSUE THREAD

**Issue by Jossnaz** [glhd/aire#72]
now I have this use case where I want an input box next to a select box
they function together

basically time select

e.g.
11:00 
in one input (with mask)
and then a select with am / pm

what is the proper way of doing that?

**Comment by Jossnaz** [comment]
currently doing it like so:

```
                        <div class="flex-1 mr-2 mb-5">
                            <label class="inline-block mb-2 font-semibold cursor-pointer text-base">1. ¿A qué hora se acostó normalmente por la noche?</label>
                            <div class="flex">
                                {{ Aire::input('q1_sleep_at')
                                ->class('tss-time-us')
                                ->groupClass('')
                                ->autoComplete('off') }}
                                {{ Aire::select(['am' => 'am', 'pm' => 'pm'], 'select')
                                ->groupClass('')
                                   ->style("min-width: 62px")
                                   ->value('pm') }}
                            </div>
                            <small class="block mt-1 font-normal text-sm text-gray-600">
                                Escriba la hora habitual en que se acuesta
                            </small>
                        </div>
```

e.g. copy paste the label outside of the supposed places... I think this is fine for the exceptional special component actually


thoughts?

**Comment by inxilpro** [comment]
All elements are macroable, and all calls in `Aire::*` are deferred to the form element. This means you could add:

```php
Form::macro('timeSelect', function() { ... });
```

And add your own custom element that can be called with `Aire::timeSelect()`.

That said, I plan on adding `Aire::label()` shortly, which will help with having to duplicate the label code.

**Comment by inxilpro** [comment]
Oh, I misspoke. You can already do `Aire::label()`!

**Comment by Jossnaz** [comment]
that was very helpful info.

I noticed that the error message would "pull the select" too far right.
e.g. the error message from the input would separate the am/pm selector 

not sure what is the best solution, but haven't looked
