### ISSUE TITLE
default_classes won't owerride classes of element

### ISSUE THREAD

**Issue by marekmez** [glhd/aire#77]
Hi,

I was trying to change default tailwind classes of an input element in config/aire.php as explained in docs. Unfortunately, class names are only added to default once. I was expecting that these will be replaced by specified in config file.

Config file:
```
'default_classes' => [
        'input' => 'form-control',
        'select' => 'form-select',
        'textarea' => 'form-control',
 ],
```

But this is the output:

```
<input type="text" class="form-control p-2 text-base rounded-sm text-gray-900" data-aire-component="input" name="given_name" id="given_name" data-aire-for="given_name">
```

 - Laravel Version: 8
 - Aire Version: 2.4.0

Thanks,
Marek

**Comment by inxilpro** [comment]
You also have to update the `variant_classes` and `validation_classes` — they're merged together.
