### ISSUE TITLE
Depreciation notices with PHP 8.1

### ISSUE THREAD

**Issue by joostdebruijn** [glhd/aire#94]
**Describe the bug**
Since PHP 8.1 there are notices when using this package, for example:

'Return type of Galahad\\Aire\\Elements\\Attributes\\Attributes::offsetGet($key) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice'

**Have you published the Aire config file?**
Yes

**Have you added custom Aire views?**
No

**What version does this affect?**
 - Laravel Version: 8.73.2
 - Aire Version: 2.4.3
 - PHP: 8.1.0
 
**Expected behavior**
I would expect there are no depreciation notices.

**Comment by inxilpro** [comment]
This should be fixed in the [2.4.4 release](https://github.com/glhd/aire/releases/tag/2.4.4). Thanks!
